spring:
  application:
    name: chromaback

  threads:
    virtual:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    encoding: 'UTF-8'
    cleanDatabase: false

  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true
      jdbc:
        schema: metadata

  batch:
    jdbc:
      initialize-schema: "always"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/chromamon-realm

  mail:
    host: mailpit
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8081

chromamon:
  csv:
    row-limit: 800