spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chromamon
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

logging:
  level:
    root: INFO
    com.ppossatto.chromaback: DEBUG