spring:
  application:
    name: chromaback

  threads:
    virtual:
      enabled: true

  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true
      jdbc:
        schema: metadata

  batch:
    jdbc:
      initialize-schema: "always"


server:
  port: 8081

chromamon:
  csv:
    row-limit: 800